Feat: Vote 기능 구현
f-lab-edu/dduikka pull request #5
Opened 2024-01-26 17:51 UTC by kimzoo2

### 투표

- 사용자가 투표를 조회한다
- 사용자가 오늘 날씨에 대한 투표한다 (뛴다 / 안 뛴다)
- 사용자가 투표를 취소한다
- 사용자가 자신의 투표 기록을 조회한다
     - 취소된 투표기록은 조회되지 않는다

2024-01-28 02:03 UTC, f-lab-inno requested changes

2024-01-28 02:03 UTC, f-lab-inno commented on src/main/java/com/flab/dduikka/domain/vote/repository/JdbcVoteRecordRepository.java
> +		Map<String, Object> param = Map.of("voteDate", voteDate);
해당 변수는 인라인화 해주어도 좋겠네요!

2024-01-28 02:03 UTC, f-lab-inno commented on src/main/java/com/flab/dduikka/domain/vote/repository/VoteRecordRepository.java
> +	VoteRecord addVote(VoteRecord voteRecord);
`VoteRepository`에서는 create라는 명칭을 사용하고 있는데, VoteRecord는 하위 엔티티로써 추가되는 개념이기 때문에 add라고 표현해주신걸까요? 혹시 그렇다 하더라도 Repository에서의 개념으로는 create가 조금 더 적절해보이긴 합니다!

2024-01-28 02:03 UTC, f-lab-inno commented on src/main/java/com/flab/dduikka/domain/vote/repository/VoteRecordRepository.java
> +	List<VoteRecord> findByVoteAndVoteType(LocalDate voteDate);
메소드명과 메소드가 하는일이 일치하지 않는것 같아요!

2024-01-28 02:03 UTC, f-lab-inno commented on src/main/resources/h2/schema.sql
> +    UNIQUE (VOTE_DATE)
아직 제가 해당 DB스키마 구조를 잘 이해하지 못해서 그럴수도 있을것 같은데, 투표일자가 유니크여도 괜찮은걸까요?

2024-01-28 15:12 UTC, kimzoo2 commented on src/main/java/com/flab/dduikka/domain/vote/repository/VoteRecordRepository.java
> +	VoteRecord addVote(VoteRecord voteRecord);
추가되는 개념이라 add라 표현했던 게 맞습니다! 생각해보니 말씀하신대로 create가 더 적절해보여 수정하도록 하겠습니다👍

2024-01-28 15:14 UTC, kimzoo2 commented on src/main/java/com/flab/dduikka/domain/vote/domain/VoteType.java
> +	}
수정하도록 하겠습니다!

2024-01-28 15:27 UTC, kimzoo2 commented on build.gradle
>  	implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // Spring Data JPA를 사용하기 위한 스타터
제외하도록 하겠습니다 😂

2024-01-29 07:55 UTC, kimzoo2 commented on src/main/java/com/flab/dduikka/domain/vote/domain/VoteRecord.java
> +	}
말씀하신대로 의존성 문제가 고려되지 않았던 것 같습니다!
VoteRecord에서 진행한 Dto -> Entity 책임을 Dto가 처리하여
고수준 레이어가 저수준 레이어에 의존하지 않도록 변경하겠습니다!

2024-01-29 08:20 UTC, kimzoo2 commented on src/main/java/com/flab/dduikka/domain/vote/domain/VoteRecord.java
> +	private LocalDateTime createdAt;
@f-lab-inno 님!
@MappedSuperclass 는 JPA 의존성이 있어야만 활용할 수 있는 어노테이션인 걸로 알고 있는데 JPA 의존성을 제거하고도 사용할 수 있는방법이 있는건지 궁금합니다!

2024-01-29 11:55 UTC, f-lab-inno commented on src/main/java/com/flab/dduikka/domain/vote/domain/VoteRecord.java
> +	private LocalDateTime createdAt;
엇 그렇네요! 요건 그럼 JPA 의존성 없이 상속구조로 공통속성을 추상화해보는 방법이 어떨지요

2024-01-30 06:44 UTC, kimzoo2 commented on src/main/java/com/flab/dduikka/domain/vote/repository/VoteRecordRepository.java
> +	List<VoteRecord> findByVoteAndVoteType(LocalDate voteDate);
수정하도록 하겠습니다😂

2024-01-30 06:45 UTC, kimzoo2 commented on src/main/java/com/flab/dduikka/domain/vote/application/VoteService.java
> +	}
생성 책임에만 집중하느라 놓쳤던 부분이었습니다. 말씀해주신 대로 스케줄러 객체로 분리하였습니다! 🙇

2024-01-30 14:13 UTC, kimzoo2 commented on src/main/java/com/flab/dduikka/domain/vote/domain/VoteRecord.java
> +	private LocalDateTime createdAt;
상속구조로 공통속성을 BaseEntity로 분리하였습니다.
[d7d2a1f](https://github.com/f-lab-edu/dduikka/pull/5/commits/d7d2a1f183dd0e29e54809cdd0ea8ee48cd6bb2b) 반영완료

2024-01-31 00:30 UTC, f-lab-inno commented on src/main/java/com/flab/dduikka/domain/vote/application/VoteRecordService.java
> +	}
너무 깔끔하게 잘 구현해주셨네요, 테스트에서도 객체로써 요구사항이 잘 드러나는것 같아요. 👍

2024-01-31 00:32 UTC, f-lab-inno commented
@kimzoo2 피드백 잘 반영해주셨습니다. 코드가 한층 더 깔끔해진것 같아요.

혹시 아직 반영해야하는데 못한 부분이 있다면 다음 PR에서 진행하시죠!

2024-01-31 00:32 UTC, merged

2024-01-31 00:37 UTC, f-lab-inno commented on src/main/java/com/flab/dduikka/domain/BaseEntity.java
> +public abstract class BaseEntity {
가지고 있는 속성에 맞게 추상화 할 명칭도 조금은 명시적이면 더 좋을것 같은데 어떠실까요? 예를 들면 `Auditable` 이라던지요!